name: An introductory GitHub Action
on:
  push:
    branches: [main]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Looks for action in <PROJECT_ROOT_DIRECTORY>/action-a
      - uses: ./Docker
        # Set a secret from GitHub
        env:
          MY_NAME: ${{secrets.MY_NAME}}
